<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'name' => 'Mesa de Partes Virtual',
                'short_description' => 'Canaliza la recepcion digital de documentos y solicitudes oficiales.',
                'department' => 'Secretaria General',
                'category' => 'Tramites documentarios',
                'usage_count' => 1284,
                'coverage' => 'Toda la institucion',
                'url' => 'https://servicios.unap.edu.pe/mesa-de-partes',
                'type' => 'api-rest',
                'status' => 'aprobado',
                'auth_type' => 'oauth2',
                'schedule' => 'full',
                'monthly_limit' => 3200,
                'tags' => ['recientes', 'masUsados', 'destacados'],
                'labels' => ['Atencion 24/7', 'Entrega digital'],
                'owner' => 'Oficina de Gestion Documentaria',
                'documentation_url' => 'https://example.edu.pe/docs/mesa-de-partes.pdf',
                'terms_accepted' => true,
                'approved_at' => now()->subDays(8),
                'versions' => [
                    [
                        'version' => '2.4.1',
                        'status' => 'available',
                        'release_date' => '2025-09-25',
                        'compatibility' => 'Web / Movil',
                        'documentation_url' => 'https://example.edu.pe/docs/mesa-de-partes-v241.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 3200,
                        'notes' => 'Version estabilizada con seguimiento en linea de expedientes.',
                    ],
                    [
                        'version' => '2.3.0',
                        'status' => 'maintenance',
                        'release_date' => '2025-07-10',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/mesa-de-partes-v230.pdf',
                        'is_requestable' => false,
                        'limit_suggestion' => null,
                        'notes' => 'Se mantiene solo para historicos, no admite nuevas solicitudes.',
                    ],
                ],
            ],
            [
                'name' => 'Solicitud de Constancias Academicas',
                'short_description' => 'Genera constancias academicas en linea con firma digital.',
                'department' => 'Direccion Academica',
                'category' => 'Servicios academicos',
                'usage_count' => 912,
                'coverage' => 'Estudiantes regulares y egresados',
                'url' => 'https://servicios.unap.edu.pe/constancias',
                'type' => 'form-web',
                'status' => 'aprobado',
                'auth_type' => 'sso',
                'schedule' => 'office',
                'monthly_limit' => 2800,
                'tags' => ['masUsados', 'destacados'],
                'labels' => ['Pago en linea', 'Disponible en PDF'],
                'owner' => 'Direccion Academica',
                'documentation_url' => 'https://example.edu.pe/docs/constancias.pdf',
                'terms_accepted' => true,
                'approved_at' => now()->subDays(5),
                'versions' => [
                    [
                        'version' => '1.9.0',
                        'status' => 'available',
                        'release_date' => '2025-10-01',
                        'compatibility' => 'Web / Punto de atencion',
                        'documentation_url' => 'https://example.edu.pe/docs/constancias-v190.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 2800,
                        'notes' => 'Incluye soporte para pagos con billetera digital.',
                    ],
                    [
                        'version' => '1.8.2',
                        'status' => 'maintenance',
                        'release_date' => '2025-06-20',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/constancias-v182.pdf',
                        'is_requestable' => false,
                        'limit_suggestion' => null,
                        'notes' => 'Se mantiene para consultas historicas.',
                    ],
                ],
            ],
            [
                'name' => 'Solicitud de Espacios Institucionales',
                'short_description' => 'Gestiona reservas de auditorios y aulas especiales para eventos institucionales.',
                'department' => 'Direccion de Laboratorios',
                'category' => 'Gestion de recursos',
                'usage_count' => 478,
                'coverage' => 'Facultad de Ingenieria',
                'url' => 'https://servicios.unap.edu.pe/espacios',
                'type' => 'api-rest',
                'status' => 'revision',
                'auth_type' => 'ninguna',
                'schedule' => 'office',
                'monthly_limit' => 1500,
                'tags' => ['destacados'],
                'labels' => ['Equipo especializado', 'Soporte presencial'],
                'owner' => 'Direccion de Laboratorios',
                'documentation_url' => 'https://example.edu.pe/docs/reservas-lab.pdf',
                'terms_accepted' => true,
                'approved_at' => null,
                'versions' => [
                    [
                        'version' => '0.9.5',
                        'status' => 'maintenance',
                        'release_date' => '2025-08-15',
                        'compatibility' => 'Web / Kiosko',
                        'documentation_url' => 'https://example.edu.pe/docs/reservas-lab-v095.pdf',
                        'is_requestable' => false,
                        'limit_suggestion' => 1500,
                        'notes' => 'En mantenimiento. Reapertura prevista para noviembre.',
                    ],
                ],
            ],
            [
                'name' => 'Certificado de Estudios',
                'short_description' => 'Genera certificados oficiales con validacion automatica.',
                'department' => 'Direccion Academica',
                'category' => 'Servicios academicos',
                'usage_count' => 1540,
                'coverage' => 'Estudiantes y egresados',
                'url' => 'https://servicios.unap.edu.pe/certificados',
                'type' => 'api-rest',
                'status' => 'aprobado',
                'auth_type' => 'oauth2',
                'schedule' => 'full',
                'monthly_limit' => 3500,
                'tags' => ['masUsados'],
                'labels' => ['Descarga inmediata', 'Validez oficial'],
                'owner' => 'Direccion Academica',
                'documentation_url' => 'https://example.edu.pe/docs/certificados.pdf',
                'terms_accepted' => true,
                'approved_at' => now()->subDays(12),
                'versions' => [
                    [
                        'version' => '2.1.0',
                        'status' => 'available',
                        'release_date' => '2025-09-12',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/certificados-v210.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 3500,
                        'notes' => 'Agrega soporte para traducciones certificadas.',
                    ],
                    [
                        'version' => '2.0.3',
                        'status' => 'available',
                        'release_date' => '2025-04-05',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/certificados-v203.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 3100,
                        'notes' => 'Version estable previa, se mantiene disponible por compatibilidad.',
                    ],
                ],
            ],
            [
                'name' => 'Inscripcion a Examenes Extraordinarios',
                'short_description' => 'Gestiona inscripciones para examenes extraordinarios y rezagados.',
                'department' => 'Oficina de Admision',
                'category' => 'Tramites estudiantiles',
                'usage_count' => 236,
                'coverage' => 'Postulantes y estudiantes regulares',
                'url' => 'https://servicios.unap.edu.pe/examenes-extra',
                'type' => 'form-web',
                'status' => 'aprobado',
                'auth_type' => 'sso',
                'schedule' => 'office',
                'monthly_limit' => 1800,
                'tags' => ['recientes'],
                'labels' => ['Responde en 48h', 'Pago en caja'],
                'owner' => 'Oficina de Admision',
                'documentation_url' => 'https://example.edu.pe/docs/examenes-extra.pdf',
                'terms_accepted' => true,
                'approved_at' => now()->subDays(2),
                'versions' => [
                    [
                        'version' => '1.3.0',
                        'status' => 'available',
                        'release_date' => '2025-10-08',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/examenes-extra-v130.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 1800,
                        'notes' => 'Incluye validacion de pagos en tiempo real.',
                    ],
                    [
                        'version' => '1.2.1',
                        'status' => 'maintenance',
                        'release_date' => '2025-03-25',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/examenes-extra-v121.pdf',
                        'is_requestable' => false,
                        'limit_suggestion' => null,
                        'notes' => 'Solo mantiene consultas de examenes anteriores.',
                    ],
                ],
            ],
            [
                'name' => 'Constancia de Egresado',
                'short_description' => 'Emite constancias oficiales de egresado con verificacion digital.',
                'department' => 'Direccion de Seguimiento al Egresado',
                'category' => 'Servicios academicos',
                'usage_count' => 765,
                'coverage' => 'Egresados',
                'url' => 'https://servicios.unap.edu.pe/constancia-egresado',
                'type' => 'api-rest',
                'status' => 'aprobado',
                'auth_type' => 'api_key',
                'schedule' => 'full',
                'monthly_limit' => 2600,
                'tags' => ['recientes', 'masUsados'],
                'labels' => ['Firma digital', 'Entrega por correo'],
                'owner' => 'Direccion de Seguimiento al Egresado',
                'documentation_url' => 'https://example.edu.pe/docs/constancia-egresado.pdf',
                'terms_accepted' => true,
                'approved_at' => now()->subDays(3),
                'versions' => [
                    [
                        'version' => '2.0.0',
                        'status' => 'available',
                        'release_date' => '2025-09-28',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/constancia-egresado-v200.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 2600,
                        'notes' => 'Incluye validacion automatica con base de datos de SUNEDU.',
                    ],
                    [
                        'version' => '1.7.5',
                        'status' => 'available',
                        'release_date' => '2025-05-12',
                        'compatibility' => 'Web',
                        'documentation_url' => 'https://example.edu.pe/docs/constancia-egresado-v175.pdf',
                        'is_requestable' => true,
                        'limit_suggestion' => 2200,
                        'notes' => 'Version previa mantenida por compatibilidad con sistemas heredados.',
                    ],
                ],
            ],
        ];

        foreach ($services as $serviceData) {
            $versions = $serviceData['versions'];
            unset($serviceData['versions']);

            $service = Service::create($serviceData);

            foreach ($versions as $version) {
                $service->versions()->create($version);
            }
        }
    }
}
